### ISSUE TITLE
安装书写错误

### ISSUE THREAD

**Issue by sanagent** [workbunny/webman-shared-cache#1]
pecl install apcu

**Comment by sanagent** [comment]
```php
# 2. 安装器安装【推荐】
curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - | sh -s apcu
```
这个报错
```shell
The script sh is meant to be used with official Docker PHP Images - https://hub.docker.com/_/php
curl: (23) Failed writing body (0 != 1395)

```

**Comment by sanagent** [comment]
配置php.ini 报错
```shell
mac-mini webman-shared-cache % ./shard-cache-enable
zsh: no such file or directory: ./shard-cache-enable
mac-mini webman-shared-cache % ls
app.php                shared-cache-enable.sh
mac-mini webman-shared-cache % 

mac-mini webman-shared-cache % 

```

**Comment by sanagent** [comment]
我没配置php.ini ，继续报错
这是代码
```php
        $key = 'cache-test';
        \Workbunny\WebmanSharedCache\Cache::set($key,1);
        var_dump(\Workbunny\WebmanSharedCache\Cache::get($key));
```
报错信息
```shell
Error: Call to undefined function Workbunny\WebmanSharedCache\apcu_store() in /www/test-webman/vendor/workbunny/webman-shared-cache/src/Cache.php:136<br />
Stack trace:<br />
#0 [internal function]: Workbunny\WebmanSharedCache\Cache::_Set('cache-test', 1)<br />

```

**Comment by chaz6chez** [comment]
> ```
> # 2. 安装器安装【推荐】
> curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - | sh -s apcu
> ```
> 
> 这个报错
> 
> ```shell
> The script sh is meant to be used with official Docker PHP Images - https://hub.docker.com/_/php
> curl: (23) Failed writing body (0 != 1395)
> ```

这是docker下安装方式



> 配置php.ini 报错
> 
> ```shell
> mac-mini webman-shared-cache % ./shard-cache-enable
> zsh: no such file or directory: ./shard-cache-enable
> mac-mini webman-shared-cache % ls
> app.php                shared-cache-enable.sh
> mac-mini webman-shared-cache % 
> 
> mac-mini webman-shared-cache % 
> ```

尝试使用 sh shared-cache-enable.sh 或 bash shared-cache-enable.sh



> 我没配置php.ini ，继续报错 这是代码
> 
> ```
>         $key = 'cache-test';
>         \Workbunny\WebmanSharedCache\Cache::set($key,1);
>         var_dump(\Workbunny\WebmanSharedCache\Cache::get($key));
> ```
> 
> 报错信息
> 
> ```shell
> Error: Call to undefined function Workbunny\WebmanSharedCache\apcu_store() in /www/test-webman/vendor/workbunny/webman-shared-cache/src/Cache.php:136<br />
> Stack trace:<br />
> #0 [internal function]: Workbunny\WebmanSharedCache\Cache::_Set('cache-test', 1)<br />
> ```

这个已修复，现在没有配置会抛出Error异常

**Comment by sanagent** [comment]
从新remove 这个包，然后重新安装，执行脚本，出现错误
```shell
mac-mini webman-shared-cache % ls
app.php                shared-cache-enable.sh
mac-mini webman-shared-cache % sh ./shared-cache-enable.sh 
配置将被创建至 ��是否继续？(y/N)
y
配置文件已创建: /usr/local/etc/php/conf.d/apcu-cache.ini
mac-mini webman-shared-cache % curl http://127.0.0.1:8686/index/apcu
Error: You need run shared-cache-enable.sh.  in i/www/test-webman/vendor/workbunny/webman-shared-cache/src/Cache.php:65<br />
Stack trace:<br />
#0 /www/test-webman/app/controller/indexController.php(115): Workbunny\WebmanSharedCache\Cache::__callStatic('info', Array)<br />

```

**Comment by chaz6chez** [comment]
> 从新remove 这个包，然后重新安装，执行脚本，出现错误
> 
> ```shell
> mac-mini webman-shared-cache % ls
> app.php                shared-cache-enable.sh
> mac-mini webman-shared-cache % sh ./shared-cache-enable.sh 
> 配置将被创建至 ��是否继续？(y/N)
> y
> 配置文件已创建: /usr/local/etc/php/conf.d/apcu-cache.ini
> mac-mini webman-shared-cache % curl http://127.0.0.1:8686/index/apcu
> Error: You need run shared-cache-enable.sh.  in i/www/test-webman/vendor/workbunny/webman-shared-cache/src/Cache.php:65<br />
> Stack trace:<br />
> #0 /www/test-webman/app/controller/indexController.php(115): Workbunny\WebmanSharedCache\Cache::__callStatic('info', Array)<br />
> ```

你是否实在docker环境下执行的？如果不是docker环境，请使用脚本的--traget参数将生成的ini放置到生效的ini路径；

--help可以查询脚本帮助信息

**Comment by sanagent** [comment]
sh ./shared-cache-enable.sh --help 命令中--help 参数并没有读取到
```shell
配置文件已创建: /usr/local/etc/php/conf.d/apcu-cache.ini
```
配置脚本显示 apcu-cache.ini 已创建，实际上并没有创建，因为这个目录不存
使用这个命令可以获取conf.d 所在的目录
```shell
mac-mini ~ % php -i |grep 'Scan this dir for additional .ini files'
Scan this dir for additional .ini files => /usr/local/etc/php/8.1/conf.d
```
将 apcu-cache.ini 放在当前php  conf.d 的目录下，运行成功
