### ISSUE TITLE
php webman 命令行报错

### ISSUE THREAD

**Issue by weijer** [workbunny/webman-shared-cache#5]
![image](https://github.com/user-attachments/assets/6aa36f32-e80e-4fcf-af75-10c354048eaf)

```
PHP Fatal error:  Type of Workbunny\WebmanSharedCache\Commands\AbstractCommand::$defaultName must not be defined (as in class Symfony\Component\Console\Command\Command) in /app/vendor/workbunny/webman-shared-cache/src/Commands/AbstractCommand.php on line 0
```

环境PHP 8.2.23

涉及文件 
vendor/workbunny/webman-shared-cache/src/Commands/AbstractCommand.php
vendor/workbunny/webman-shared-cache/src/Commands/WorkbunnyWebmanSharedCacheClean.php
vendor/workbunny/webman-shared-cache/src/Commands/WorkbunnyWebmanSharedCacheEnable.php
vendor/workbunny/webman-shared-cache/src/Commands/WorkbunnyWebmanSharedCacheHRecycle.php

![image](https://github.com/user-attachments/assets/856a3039-9e85-42ec-ac91-e7dc55e4042e)

Symfony\Component\Console\Command\Command

![image](https://github.com/user-attachments/assets/1601c5e6-490f-484c-96c3-d9afa89cbf53)

**Comment by chaz6chez** [comment]
https://github.com/workbunny/webman-shared-cache/releases/tag/0.5.4
